source-file ~/.config/tmux/tmux.tpm.conf
source-file ~/.config/tmux/tmux.reset.conf
set-option -g default-terminal 'xterm-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

set-option -g extended-keys on
set -as terminal-features 'xterm*:extkeys'

set -g mouse on
set -g prefix ^A
set -g base-index 1              # start indexing windows at 1 instead of 0
setw -g pane-base-index 1
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 1000000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g allow-passthrough on
set -g set-clipboard on          # use system clipboard
set -g status-position top       # macOS / darwin style
set -g default-terminal "${TERM}"
setw -g mode-keys vi
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'


set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @plugin 'vaaleyard/tmux-dotbar'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
set -g @plugin 'alexwforsythe/tmux-which-key'  # prefix + space
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'dreknix/tmux-primary-ip'

set -g @plugin 'omerxx/tmux-sessionx'          # prefix + o


set -g @sessionx-bind 'o'
set -g @sessionx-x-path '~/personal_projects'
set -g @sessionx-window-height '85%'
set -g @sessionx-window-width '75%'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-filter-current 'false'
set -g @sessionx-preview-enabled 'true'
set -g @continuum-restore 'off'
set -g @resurrect-strategy-nvim 'session'

# supposing you use catppuccin moccha
set -g @tmux-dotbar-bg "default"
set -g @tmux-dotbar-fg "#585b70"
set -g @tmux-dotbar-fg-current "#cdd6f4"
set -g @tmux-dotbar-fg-session "#9399b2"
set -g @tmux-dotbar-fg-prefix "#cba6f7"
set -g @tmux-dotbar-position top

# set left and right status bar
run '#{TMUX_PLUGIN_MANAGER_PATH}/tpm/tpm'
