[bar.default]
capsule_radius = 0
end = [
    "widget",
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "brightness",
    "volume",
    "battery",
    "control-center"
]
margin_ends = 0
radius = 0
start = [ "launcher", "wallpaper", "workspaces", "media" ]
widget_spacing = 9

[battery.device."/org/freedesktop/UPower/devices/phone_dev_F0_D7_93_0C_57_CF"]
warning_threshold = 10

[brightness]
enable_ddcutil = true
sync_all_monitors = true

[calendar]
enabled = true

    [calendar.account.personal_google]
    type = "google"

[config]

[keybinds]
down = [ "Down", "Ctrl+n" ]
up = [ "Up", "Ctrl+p" ]

[location]
auto_locate = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-widget-0000000000000001", "lockscreen-widget-0000000000000002" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 192.0
    box_width = 528.0
    cx = 960.0
    cy = 268.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 176.0
    box_width = 384.0
    cx = 960.0
    cy = 540.0
    output = "eDP-1"
    rotation = 0.0
    type = "weather"

[plugin_settings."alexander/mimir"]
api_key = "sk-h2oSHshBa12R9WhIxxNfeWcuYDOfZWgCaHWhecPt74CohXBw7CpvGZ3yAbEIDrOG"
chat_position = "top_left"

[plugin_settings."alexander/screen-toolkit"]
panel-full_placement = "attached"
record-audio-in = true
record-audio-out = true

[plugins]
enabled = [ "alexander/screen-toolkit" ]

[shell]
corner_radius_scale = 0.0
polkit_agent = true

    [shell.greeter_sync]
    auto_sync = true

[templates.nvim-base16]
input_path = "~/.config/nvim/lua/matugen-template.json"
output_path = "~/.config/nvim/lua/matugen.json"

[templates.rofi]
input_path = "~/.config/noctalia/templates/rofi.rasi"
output_path = "~/.config/rofi/matugen/colors.rasi"

[theme]
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "ghostty", "hyprland", "qt", "starship" ]
    community_ids = [ "zen-browser", "rofi", "fastfetch", "lazygit" ]

[wallpaper.default]
path = "/home/eslamallam/Pictures/Wallpapers/Red_Eclipse.png"

[wallpaper.last]
path = "/home/eslamallam/Pictures/Wallpapers/Red_Eclipse.png"

[wallpaper.monitors.eDP-1]
path = "/home/eslamallam/Pictures/Wallpapers/Red_Eclipse.png"

[widget.control-center]
glyph = "navigation-filled"

[widget.session]
enabled = false

[widget.tray]
hidden = [ "nm-applet" ]

[widget.widget]
type = "alexander/screen-toolkit:widget"
